### ISSUE TITLE
AttributeError: module 'chainlit' has no attribute 'langchain_factory'

### ISSUE THREAD

**Issue by ashishpatel26** [leehanchung/llm-pdf-qa-workshop#1]
```python
(tensorflow) D:\LLMS\Chainlit\llm-pdf-qa-workshop>chainlit run app/app.py -w     
Traceback (most recent call last):
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ibm26\.conda\envs\tensorflow\Scripts\chainlit.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\chainlit\cli\__init__.py", line 154, in chainlit_run
    run_chainlit(target)
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\chainlit\cli\__init__.py", line 47, in run_chainlit
    load_module(config.run.module_name)
  File "C:\Users\ibm26\.conda\envs\tensorflow\lib\site-packages\chainlit\config.py", line 242, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\LLMS\Chainlit\llm-pdf-qa-workshop\app/app.py", line 91, in <module>
    @cl.langchain_factory(use_async=True)
AttributeError: module 'chainlit' has no attribute 'langchain_factory'
```

**Comment by leehanchung** [comment]
Fixing soon, need to bump versions

**Comment by leehanchung** [comment]
Fixed in the latest main
